### ISSUE TITLE
0x00 keys and 0x11 keys return same pub key

### ISSUE THREAD

**Issue by obscuren** [haltingstate/secp256k1-go#6]
I'm currently investigating an issue I'm having with a fork of your repo https://github.com/obscuren/secp256k1-go (full length pub keys) and I've come across an issue (I suspect in secp256k1 it self) with the following keys:

`0000000000000000000000000000000000000000000000000000000000000000` and `1111111111111111111111111111111111111111111111111111111111111111`

Both will return the same public key `034f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa` or full length `044f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa385b6b1b8ead809ca67454d9683fcf2ba03456d6fe2c4abe2b07f0fbdbb2f1c1`

**Comment by ebuchman** [comment]
Note if you try to sign with "000..." you get "Invalid secret key". Perhaps that error should also be returned by `GeneratePubKey`

Note I have found other problems with this lib and am working on putting up a repo for some more testing.

**Comment by ebuchman** [comment]
https://github.com/ebuchman/secp256k1-tests/

**Comment by haltingstate** [comment]
>Note if you try to sign with "000..." you get "Invalid secret key". Perhaps that error should also be returned by GeneratePubKey

I added a check to ensure that the secret key is valid if its used to generate a public key.

```go
	//ensure that private key is valid
	ret := C.secp256k1_ecdsa_seckey_verify(seckey_ptr)
	if ret != 1 {
		log.Panic("PubkeyFromSeckey: invalid seckey")
	}
	//create public key from seckey
	ret = C.secp256k1_ecdsa_pubkey_create(
		pubkey_ptr, &pubkey_len,
		seckey_ptr, 1)
```

I should add support for recovering the uncompressed key from the compressed version. However, no one uses that but ethereum. Everyone just uses the compressed keys for Bitcoin now. Having two formats causes confusion.

**Comment by haltingstate** [comment]
It is very odd that "000.." and "FFF..." should generate the same public key

p = FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE FFFFFC2F

G = 04 79BE667E F9DCBBAC 55A06295 CE870B07 029BFCDB 2DCE28D9 59F2815B 16F81798 483ADA77 26A3C465 5DA4FBFC 0E1108A8 FD17B448 A6855419 9C47D08F FB10D4B8

```C
void static secp256k1_ecmult_gen(secp256k1_gej_t *r, const secp256k1_num_t *gn) {
    secp256k1_num_t n;
    secp256k1_num_init(&n);
    secp256k1_num_copy(&n, gn);
    const secp256k1_ecmult_consts_t *c = secp256k1_ecmult_consts;
    secp256k1_gej_set_infinity(r);
    for (int j=0; j<64; j++) {
        secp256k1_ge_t add;
        int bits = secp256k1_num_shift(&n, 4);
        for (int k=0; k<sizeof(secp256k1_ge_t); k++)
            ((unsigned char*)(&add))[k] = c->prec[j][k][bits];
        secp256k1_gej_add_ge(r, r, &add);
    }
    secp256k1_num_free(&n);
    secp256k1_gej_add_ge(r, r, &c->fin);
}
```

I dont see it in there

```C
void static secp256k1_num_set_bin(secp256k1_num_t *r, const unsigned char *a, unsigned int alen) {
    assert(alen > 0);
    assert(alen <= 64);
    int len = mpn_set_str(r->data, a, alen, 256);
    assert(len <= NUM_LIMBS*2);
    r->limbs = len;
    r->neg = 0;
    while (r->limbs > 1 && r->data[r->limbs-1]==0) r->limbs--;
}
```

```C
typedef struct {
    mp_limb_t data[2*NUM_LIMBS];
    int neg;
    int limbs;
} secp256k1_num_t;
```

I hate the GNU large number library. I might end up writing thing in Golang. Just horrible.

**Comment by haltingstate** [comment]
Just to be certain, take "FFF...." and subtract one from it and make sure its not generating the same pubkey as "000...".  Replace the first byte with EF try again, then FE. Then start with "FFF..." then replace the last byte with an EF, then FE.

That will tell us whether its rounding to zero for values over P.

**Comment by obscuren** [comment]
To be clear `0000` and `11111` (hex) are the same. Didn't test with `FFFF`
